name: Performance - Gatling Simulation
run-name: Performance - ${{ github.event.inputs.simulation_class }}

on:
  workflow_dispatch:
    inputs:
      repo_url:
        description: 'Git repository URL'
        required: true
        default: 'https://github.com/user/repo.git'
      branch:
        description: 'Branch to clone'
        required: false
        default: 'main'
      simulation_class:
        description: 'Gatling Simulation Class'
        required: true
        default: 'simulations.customers.CustomersSimulation'
      enviroment:
        description: 'Ambiente para ejecutar prueba de performance'
        required: true
        default: 'perf'

jobs:
  run-gatling:
    runs-on: ubuntu-latest

    steps:

      # ✅ Checkout vacío (no el repo actual)
      - name: Checkout pipeline repo
        uses: actions/checkout@v4

      # ✅ Clonar repo dinámico
      - name: Clone target repo
        run: |
          git clone -b ${{ github.event.inputs.branch }} ${{ github.event.inputs.repo_url }} project
          cd project
          ls -la

      # ✅ Setup Java
      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      # ✅ Cache Maven (opcional pero recomendado)
      - name: Cache Maven
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: maven-${{ runner.os }}-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            maven-${{ runner.os }}

      # ✅ Ejecutar Gatling
      - name: Run Gatling Simulation
        working-directory: ./project
        run: |
          echo "Running simulation: ${{ github.event.inputs.simulation_class }}"
          
          mvn clean gatling:test \
          -Dkarate.options="--debug" -Dgatling.simulationClass=${{ github.event.inputs.simulation_class }}

      
       # ✅ Verificar carpeta results
      - name: List Gatling results
        working-directory: ./project
        run: |
          echo "Listing results folder..."
          ls -R target/gatling || true
          ls -R results || true

      # ✅ Subir resultados como artifact
      - name: Upload Gatling Report
        uses: actions/upload-artifact@v4
        with:
          name: gatling-results
          path: |
            project/target/gatling/**
            project/results/**
          if-no-files-found: warn
